### PR TITLE
Prepare for nextVersion

### PR DESCRIPTION
**Pull request by donavanbecker**
- Update Homebridge Package & FFmpeg Version
- Resolve warnings from GitHub actions

### CODE REVIEW

**Comment by bwp91** [comment]
@donavanbecker checks failed do we know why?

**Comment by donavanbecker** [comment]
Wait for [homebridge-apt-pkg](https://github.com/homebridge/homebridge-apt-pkg/actions/runs/6756124352/job/18365257452) to finish and I will rerun them again

**Comment by tdiekel** [comment]
@donavanbecker the new [homebridge-apt-pkg](https://github.com/homebridge/homebridge-apt-pkg/releases) release is available and has version 1.1.2.

**Comment by tdiekel** [comment]
The build is failing because the [ffmpeg-for-homebridge](https://github.com/homebridge/ffmpeg-for-homebridge/releases) release v2.1.1 has no debian build which the [Dockerfile](https://github.com/homebridge/docker-homebridge/blob/31d86debf117593fdfcc0759ce35f08f27c2cd55/Dockerfile#L59C88-L59C102) expects. I guess simply changing it from `ffmpeg-debian-${FFMPEG_ARCH}.tar.gz` to `ffmpeg-alpine-${FFMPEG_ARCH}.tar.gz` should fix it.

**Comment by donavanbecker** [comment]
Thanks @tdiekel!

**Review by NorthernMan54 — APPROVED** [review]

**Pull request merged**
