### PR TITLE
Add Support for ffmpeg

### PR DESCRIPTION
**Pull request by AppleTechy**
This adds support for Homebridge-nest-cam and Homebridge-camera-ffmpeg. Both of which require ffmpeg. This update has it install ffmpeg and the related ffmpeg libraries. (I tested this with homebridge-nest-cam and it worked). Let me know if you need anything else for me

### CODE REVIEW

**Comment by oznu** [comment]
Thanks for your PR @AppleTechy,

Wouldn't this be the same as starting the container like this?

```
docker run -e "PACKAGES=ffmpeg,ffmpeg-libs" oznu/homebridge
```

**Comment by AppleTechy** [comment]
Hello. Is the “e” command do the same thing as adding the run command? I am new to Docker so I don’t really know all the ins and outs of it. I can try giving that a run and seeing if it still works. Is there any reason not to have ffmpeg just built in since the camera plugins require it?

**Comment by AppleTechy** [comment]
Hello. ~~Is the “e” command do the same thing as adding the run command? I am new to Docker so I don’t really know all the ins and outs of it. I can try giving that a run and seeing if it still works.~~ Is there any reason not to have ffmpeg just built in since the camera plugins require it?
Edit: I tested that and it accomplishes the same thing. So I see 2 options: 1) This gets merged or 2) I create a different PR that just edits the readme to add that hint in there to add the ffmpeg and lib packages and then just close this pr. Its up to you, like I said I am by no means an expert at Docker so I am not sure if one way is better than the other.

**Comment by oznu** [comment]
Yes, in this case `-e "PACKAGES=ffmpeg,ffmpeg-libs"` is doing the same thing as adding the run command in the Dockerfile.

Many people use different plugins and including *everything* would bloat the container. For example, just adding `ffmpeg` and `ffmpeg-libs` adds 40mb to the image size.

I do mention packages in the readme. Perhaps adding `ffmpeg-libs` to the example there would be enough of a hint/

**Comment by AppleTechy** [comment]
Since I am new to Docker, I had no clue you could simply do that, I thought you had to edit the dockerfile. I think just adding it into the readme would be enough.(Not sure of any other requirements for plugins, that can't just be installed as dependencies via node)

**Comment by oznu** [comment]
Added section for ffmpeg in readme.

https://github.com/oznu/docker-homebridge#3-need-ffmpeg

**Comment by AppleTechy** [comment]
Thanks.👍

**Comment by VeniceNerd** [comment]
This is cool!

> You can enable ffmpeg by adding this environment variable to your run command or docker-compose.yml:
> 
> PACKAGES=ffmpeg,ffmpeg-libs

Does that ffmpeg library also support omx transcoding? The best plugin I’d like to use requires omx on pi:

> On Raspberry Pi you might want to use OMX for transcoding as CPU on the board is too slow. In that case, make sure the ffmpeg you installed has h264_omx support. There are pre-compiled deb online if you don't want to compile one yourself.

Also, where in the docker-compose.yml would you need to add that line?

**Comment by VeniceNerd** [comment]
@oznu would it be possible for me to install this ffmpeg package in one of my containers?

https://github.com/legotheboss/homebridge-camera-ffmpeg-omx

Apparently this one includes omx transcoding and is recommended by the author of the Nest-cam Homebridge plugin. Or is this slimply not possible with a “docked’’ homebridge install?

I guess if it’s not possible I could purchase a dedicated Pi3 and just run regular homebridge on it for just this plugin. Would love to know your thoughts.

**Comment by oznu** [comment]
The omx libs would not work in the default image based on Alpine Linux, however I now have a Debian Stretch version of this image which might work.

https://github.com/oznu/docker-homebridge#4-try-the-debian-tag

**Comment by VeniceNerd** [comment]
@oznu Thanks for looking into it! At this point I think I will just keep everything the way it is and accept that I can not use the HomeBridge-Nest-Cam plugin on this Pi. I may look into getting another Pi for just this purpose or running it on my iMac.

Thanks! :)

**Pull request closed without merging**
