### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by n0rt0nthec4t**
Updated based image to ubuntu 24.04 noble (LTS)
Updated Homebridge APT package to 1.3.10
Updated ffmpeg-for-homebridge to 2.1.7
Updated S6 overlay package to 3.2.0.2

## :recycle: Current situation

_Describe the current situation. Explain current problems, if there are any. Be as descriptive as possible (e.g., including examples or code snippets)._

## :bulb: Proposed solution

_Describe the proposed solution and changes. How does it affect the project? How does it affect the internal structure (e.g., refactorings)?_

## :gear: Release Notes

_Provide a summary of the changes or features from a user's point of view. If there are breaking changes, provide migration guides using code examples of the affected features._

## :heavy_plus_sign: Additional Information

_If applicable, provide additional context in this section._

### Testing

_Which tests were added? Which existing tests were adapted/changed? Which situations are covered, and what edge cases are missing?_

### Reviewer Nudging

_Where should the reviewer start? what is a good entry point?_

### CODE REVIEW

**Comment by NorthernMan54** [comment]
Homebridge and FFMPEG versions come from here 
https://github.com/homebridge/docker-homebridge/blob/67d821f0ab88b31970a27f1c348689b7f52b26b7/.github/workflows/main.yml#L60

So changing the version there is irrelevant ( We have portions of the build automated, so it may not be easy to identify 

For people currently running the image, and if we change the OS version, is it going to breaking anything for them ?  Does this need impact testing before releasing to the world ?

With dependabot, I think I'm going to try this - 
image

**Comment by n0rt0nthec4t** [comment]
perhaps create a "test"  release on docker?

**Comment by NorthernMan54** [comment]
That's what I'm thinking as well, now does the automation have an option for that, need to look deeper

**Comment by n0rt0nthec4t** [comment]
Also, why is S6 overlay used? Seems to make things more complex

**Comment by NorthernMan54** [comment]
S6 Enables multiple processes ( homebridge, and the various child bridges )

**Comment by NorthernMan54** [comment]
Local testing is available via `test-build-local.sh` - it will build an image

What I was concerned about was the plugins that leverage node-gyp and locked to the current OS and NodeJS Release - what happens to those in a users environment when the OS updates

**Comment by n0rt0nthec4t** [comment]
Yep, the local test built an image. I think we just have to "break" stuff to move forward. We're running on an outdated OS with known security issues.

**Comment by NorthernMan54** [comment]
Did you get a moment to try it ?  Did it break plugins using node-gyp ?

**Comment by n0rt0nthec4t** [comment]
Trie local, and starts up. No what plugins use node-gyp.. still suggest getting a testing tag release going in docker and see feedback from the community?

**Comment by NorthernMan54** [comment]
I published the current bundle today, and will look at further testing of this next week

**Comment by jakepez** [comment]
Is there an image I can pull? For some reason my docker on my Qnap won't build the image (errors out with dependency problems for systemd, cron-daemon-common).

I'm happy to test if I can pull an image from someone.

**Pull request closed without merging**
