### PR TITLE
ubuntu:24.04

### PR DESCRIPTION
**Pull request by NorthernMan54**
@n0rt0nthec4t @jakepez

So I had some free time today, and finally put this change thru the paces, and it looks really good.

I was able to take a plugin, that used node-gyp, and use the updated Docker ubuntu version without any issues.

Any last comments before I merge this ?

PS - Am still thinking about test versions at some point

### CODE REVIEW

**Comment by n0rt0nthec4t** [comment]
My only comment would be for the test version, is perhaps start that soon with a homebridge 2.0 one since that’s going to cause issues.  Maybe even include config- ui- x 5 as that breaks stuff going by the upcoming warning?

**Comment by NorthernMan54** [comment]
The homebridge-config-ui-x version 5, is due to dropping of support for NodeJS 16 and armv6.  Which the docker image is not impacted by.   Technically I could update the image to it today.

HB 2.0 is a different discussion though.  Am thinking that the end users most impacted would be the low touch people, who would be unlikely to try a test version.  And would need to just have a good rollback strategy in place for them.  ie how to change docker-compose.yml to use a particular version and not latest.

I had been thinking a lot about new tags, and will be exploring a beta tag shortly.

**Comment by n0rt0nthec4t** [comment]
Maybe the easiest way is to create a beta branch and do development from there. The GitHub action can push to dockerhub with that branches tag

**Comment by NorthernMan54** [comment]
The challenge is that the Docker image uses homebridge-apt-pkg to install and configure homebridge, so I first need to create a test APT package and go from there.

What I was envisioning was a homebridge-apt-pkg with a BETA flag, which would pickup the latest beta of everything

**Pull request merged**
